//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceTest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc
    {
        public int DocId { get; set; }
        public int ClientId { get; set; }
        public int AccountId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Client Client { get; set; }
    }
}
